---
title: "Feature engineering using recipe"
author: "Muhammed Hashi"
date: '2022-08-05'
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidymodels)
library(tidyverse)
library(scales)
library(lubridate)
library(themis)
library(kknn)
hotels <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv")
```

```{r}
hotels %>% 
  select(children, babies) %>% 
  sample_n(size=20)
```

```{r}
hotel_stay <- hotels %>% 
  filter(is_canceled==0) %>% 
  mutate(children = case_when(
    children + babies > 0 ~ "children",
                              TRUE ~ "none"),
    required_car_parking_spaces = case_when(
      required_car_parking_spaces > 0 ~ "parking",
      TRUE ~ "none"
    )) %>% 
  select(-is_canceled, -babies, reservation_status)
  

hotel_stay %>% 
  count(children)
```


```{r}
library(skimr)

skim(hotel_stay)
```

```{r}
hotel_stay %>% 
  mutate(arrival_date_month = factor(arrival_date_month,
                                     levels = month.name)) %>% 
  count(hotel,arrival_date_month, children) %>% 
  group_by(hotel, children) %>% 
  mutate(proportion = n/ sum(n)) %>% 
  ggplot(aes(arrival_date_month, proportion, fill=children)) +
  geom_col(position = 'dodge') + 
  scale_x_discrete(guide = guide_axis(n.dodge = 3)) +
  scale_y_continuous(labels = percent_format()) +
  theme_minimal() +
  facet_wrap( ~ hotel, nrow = 2)
```

## checking whether people with children are more likely to need more parking space


```{r}
hotel_stay %>% 
  mutate(arrival_date_month = factor(arrival_date_month,
                                     levels = month.name)) %>% 
  count(hotel,required_car_parking_spaces, children) %>% 
  group_by(hotel, children) %>% 
  mutate(proportion = n/ sum(n)) %>% 
  ggplot(aes(required_car_parking_spaces, proportion, fill=children)) +
  geom_col(position = 'dodge') + 
  scale_x_discrete(guide = guide_axis(n.dodge = 3)) +
  scale_y_continuous(labels = percent_format()) +
  theme_minimal() +
  facet_wrap( ~ hotel, nrow = 2)
```


```{r}
library(GGally)

hotel_stay %>% 
  select(children, adr, required_car_parking_spaces,
         total_of_special_requests) %>% 
  ggpairs(aes(color=children))

```


## building model using recipe


```{r}
hotel_df <-hotel_stay %>% 
  select(children, hotel, arrival_date_month, meal,
         adr, required_car_parking_spaces, total_of_special_requests, stays_in_week_nights,
         stays_in_weekend_nights) %>% 
  mutate_if(is.character, factor)

hotel_df
```



```{r}
set.seed(234)
 
hotels_split <- initial_split(hotel_df, prop = 0.80)
hotel_train <- training(hotels_split)
hotel_test <- testing(hotels_split)

dim(hotel_train)
dim(hotel_test)
```



```{r Data-prepocessing-and-feature-engineering}
hotel_rec <- recipe(children ~ ., data = hotel_train) %>% 
  step_downsample(children) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv() %>% 
  step_normalize(all_numeric()) %>% 
  prep()
  
  hotel_rec
  
 test_prop <-  bake(hotel_rec, new_data = hotel_test)
 
 bake(hotel_rec, new_data = hotel_train)
 
 juice(hotel_rec)
```


## setting up the model

```{r}
knn_spec <-nearest_neighbor() %>% 
  set_engine("kknn") %>% 
  set_mode('classification')


hotels_workflow <- workflow() %>% 
  add_recipe(hotel_rec) %>% 
  add_model(knn_spec)

hotels_workflow



knn_fit <-knn_spec %>% 
  fit(children ~ ., data=juice(hotel_rec))

knn_fit
```

```{r}
tree_specs <-decision_tree() %>% 
  set_engine('rpart') %>% 
  set_mode('classification')

tree_specs

tree_fit <- tree_specs %>% 
  fit(children ~., data=juice(hotel_rec))

tree_fit
```

## evaluate models

```{r}
set.seed(234)
validation_split <-mc_cv(hotel_train, prop = 0.90, strata = children)

validation_split

fit_resamp <-fit_resamples(
  knn_spec,
  hotel_rec,
  validation_split,
  control=control_resamples(save_pred = TRUE))


fit_resamp %>% 
  collect_metrics()

tree_resamp <-fit_resamples(
  tree_specs,
  hotel_rec,
  validation_split,
  control=control_resamples(save_pred = TRUE))

tree_resamp %>% 
  collect_metrics()
```


```{r}
fit_resamp %>% 
  unnest(.predictions)

tree_resamp %>% 
  unnest(.predictions)
```



```{r}
fit_resamp %>% 
  unnest(.predictions) %>% 
  mutate(model = 'knn') %>% 
  bind_rows(tree_resamp %>% unnest(.predictions) %>% 
              mutate(model = "rpart")) %>% 
  group_by(model) %>% 
  roc_curve(children, .pred_children) %>% 
  autoplot()
```

```{r}
fit_resamp %>% 
  unnest(.predictions) %>% 
  conf_mat(children, .pred_class) %>% 
  autoplot()

fit_resamp %>% 
  unnest(.predictions) %>% 
  conf_mat(children, .pred_class) %>% 
  autoplot(type='heatmap')

```


```{r}
knn_fit %>% 
  predict(new_data=test_prop, type='prob') %>% 
  mutate(truth = hotel_test$children) %>% 
  roc_auc(truth, .pred_children)

knn_fit %>% 
  predict(new_data=test_prop, type='prob') %>% 
  mutate(truth = hotel_test$children) %>% 
  roc_curve(truth, .pred_children) %>% 
  autoplot()
```


```{r}
tree_fit %>% 
  predict(new_data=test_prop, type='prob') %>% 
  mutate(truth = hotel_test$children) %>% 
  roc_auc(truth, .pred_children)

tree_fit %>% 
   predict(new_data=test_prop, type='prob') %>% 
  mutate(truth = hotel_test$children) %>% 
  roc_curve(truth, .pred_children) %>% 
  autoplot()
```




```{r}
knn_test <-knn_fit %>% 
  predict(new_data=test_prop, type='prob') %>% 
  mutate(truth = hotel_test$children) %>% 
  mutate(model = 'knn')
  
  tree_test <-tree_fit %>% 
    predict(new_data=test_prop, type='prob') %>% 
              mutate(truth=hotel_test$children) %>% 
            mutate(model='rpart')
  
  
  bind_rows(knn_test, tree_test) %>% 
    group_by(model) %>% 
    roc_curve(truth, .pred_children) %>% 
    autoplot()
```










